name: Publish package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Next package version. patch, minor, major or specific version.
        required: true
        default: patch

jobs:
  publish_package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Release
        run: sh scripts/release.sh
        env:
          PUBLISH_VERSION: ${{ github.event.inputs.version }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          tags: true
